// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaUzGXLg5HMOu9IofzLFdN2Uh_4Ztt0b8',
    appId: '1:410581225858:web:9acf155f7c80d9a4d3bf9b',
    messagingSenderId: '410581225858',
    projectId: 'sellerplus-15e34',
    authDomain: 'sellerplus-15e34.firebaseapp.com',
    databaseURL: 'https://sellerplus-15e34-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sellerplus-15e34.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJCyIf9UlBHBXZ4XTcdsTd2bxY7nPWey0',
    appId: '1:410581225858:android:dc0d6de4a7a35930d3bf9b',
    messagingSenderId: '410581225858',
    projectId: 'sellerplus-15e34',
    databaseURL: 'https://sellerplus-15e34-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sellerplus-15e34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPzRTUSts2oAd0VB4aG14La09l5cWoaXc',
    appId: '1:410581225858:ios:bf8527abf2b4e049d3bf9b',
    messagingSenderId: '410581225858',
    projectId: 'sellerplus-15e34',
    databaseURL: 'https://sellerplus-15e34-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sellerplus-15e34.appspot.com',
    iosBundleId: 'com.example.sellerplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPzRTUSts2oAd0VB4aG14La09l5cWoaXc',
    appId: '1:410581225858:ios:831a50040d91ea86d3bf9b',
    messagingSenderId: '410581225858',
    projectId: 'sellerplus-15e34',
    databaseURL: 'https://sellerplus-15e34-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sellerplus-15e34.appspot.com',
    iosBundleId: 'com.example.sellerplus.RunnerTests',
  );
}
